server:
  port: 8084

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://${postgres-url}:5432/devdojo
    username: devdojo_usr
    password: ${postgres-passwd}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: true

jwt:
  config:
    type: signed
